name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: 
          - '5.6'
          - '7.0'
          - '7.1'
        #   - '7.2'
          # - '8.0'
          # - '8.1'
          # - '8.2'
          # - '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values:  zend.assertions=1,  assert.exception=1

      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run the unit tests
        run: |
          vendor/bin/phpspec --version
          vendor/bin/phpspec run -f pretty